# Generated by Django 5.2 on 2025-04-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingsession_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['-start_time']},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
