# Generated by Django 5.2 on 2025-04-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_alter_shift_options_remove_shift_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='captureticket',
            options={'managed': False, 'ordering': ['-DateMasuk']},
        ),
        migrations.AlterModelTable(
            name='captureticket',
            table='CaptureTickets',
        ),
    ]
